/**
 * Access to the QWorld-derived lab question bank.
 *
 * The bank is generated by `scripts/extract-lab-questions.py` from the
 * vendored notebooks. This module gives the rest of the app a typed, indexed
 * view of it instead of every caller re-reading and re-shaping the JSON.
 */

import bank from '@/data/labs/lab-questions.json';

export type Difficulty = 'easy' | 'medium' | 'complex';

export interface LabQuestion {
  id: string;
  topic: string;
  title: string;
  prompt: string;
  starterCode?: string;
  solution?: string;
  explanation?: string;
  source?: string;
  difficulty: Difficulty;
  /** Certification this topic maps to, when known. */
  cert?: string;
  /** Populated when the question corresponds to a seeded Lab row. */
  labId?: number;
}

export interface LabTopic {
  id: string;
  name: string;
  cert?: string;
  questions: LabQuestion[];
}

/**
 * Shape as written by `scripts/extract-lab-questions.py`.
 *
 * Note the key names: the generator emits `slug` and `certification`, not `id`
 * and `cert`. Reading the wrong ones makes every question look untagged, which
 * is exactly how the certification coverage appeared to be missing.
 */
interface RawBank {
  generatedFrom: string;
  topics: Array<{
    slug?: string;
    id?: string;
    name?: string;
    certification?: string;
    cert?: string;
    questions: LabQuestion[];
  }>;
}

const raw = bank as unknown as RawBank;

export const TOPICS: LabTopic[] = raw.topics.map((topic, index) => ({
  id: topic.slug ?? topic.id ?? topic.questions[0]?.topic ?? `topic-${index}`,
  name: topic.name ?? topic.slug ?? `Topic ${index + 1}`,
  cert: topic.certification ?? topic.cert,
  // Propagate the topic's certification onto each question so callers can
  // filter by cert without walking back up to the topic.
  questions: topic.questions.map((q) => ({
    ...q,
    cert: q.cert ?? topic.certification ?? topic.cert,
  })),
}));

const BY_ID = new Map<string, LabQuestion>();
for (const topic of TOPICS) {
  for (const question of topic.questions) {
    BY_ID.set(question.id, question);
  }
}

/**
 * How a question can be graded.
 *
 * Only a minority of the QWorld solutions are self-contained circuits that run
 * and measure — most are teaching snippets (one is a classical coin-flip
 * demo). Auto-grading by comparing measurement distributions is therefore only
 * honest for the runnable ones; the rest fall back to running the learner's
 * code and revealing the reference. Pretending otherwise would mark correct
 * work as wrong.
 */
export type GradingMode = 'distribution' | 'execution' | 'self-check';

export function gradingMode(question: LabQuestion): GradingMode {
  const solution = question.solution;
  if (!solution) return 'self-check';

  const buildsCircuit = /\b(Circuit|QuantumCircuit)\s*\(/.test(solution);
  const measures = /\.measure(_all)?\s*\(/.test(solution);
  const runs = /\.run\s*\(/.test(solution);

  if (buildsCircuit && measures && runs) return 'distribution';
  if (buildsCircuit) return 'execution';
  return 'self-check';
}

export function getQuestionById(id: string): LabQuestion | undefined {
  return BY_ID.get(id);
}

export function getTopic(id: string): LabTopic | undefined {
  return TOPICS.find((topic) => topic.id === id);
}

export function questionsForTopic(
  topicId: string,
  difficulty?: Difficulty,
): LabQuestion[] {
  const topic = getTopic(topicId);
  if (!topic) return [];
  return difficulty
    ? topic.questions.filter((q) => q.difficulty === difficulty)
    : topic.questions;
}

export function allQuestions(): LabQuestion[] {
  return [...BY_ID.values()];
}

/** Coverage summary — used by the admin dashboard and the content audit. */
export function bankStats() {
  const questions = allQuestions();
  const byDifficulty: Record<string, number> = {};
  const byCert: Record<string, number> = {};

  for (const q of questions) {
    byDifficulty[q.difficulty] = (byDifficulty[q.difficulty] ?? 0) + 1;
    const cert = q.cert ?? 'untagged';
    byCert[cert] = (byCert[cert] ?? 0) + 1;
  }

  return {
    total: questions.length,
    topics: TOPICS.length,
    byDifficulty,
    byCert,
    withSolution: questions.filter((q) => q.solution).length,
    withExplanation: questions.filter((q) => q.explanation).length,
    withStarter: questions.filter((q) => q.starterCode).length,
  };
}
